### ISSUE TITLE
GPU util training from scratch

### ISSUE THREAD

**Issue by chenshihfang** [microsoft/GenerativeImage2Text#28]
Hi,
thanks for your work.
I am curious about how many GPUs you use when training.
Because I infer an image in single 3090,
It occupies 75% GPU utilization and inference about a second per image (GIT_LARGE_COCO)
So I guess training with 512 batches needs a lot of GPUs?

BTW, how can I speed up the inference speed when I have multiple "different classes"?
(e.g. multiple batches for different frames)
currently, the inference FPS is 1.

**Comment by amsword** [comment]
one thing you can try is to use a data loader so that the data can be loaded when the model is running inference. So far, the existing code in this repo is sequentially load image & decode it. Using a data loader to hide the data loading might help.

For training, the GPUs I use normally contains 32 GB, with deespeed/fp16. By default, it is fp32 here in the example code. You can wrap it also with deepspeed/fp16/zero=1, which can save memory.

**Comment by chenshihfang** [comment]
@amsword 
Thank you for your reply.

I think the major computation cost is on the model calling part.
![image](https://user-images.githubusercontent.com/113094161/203200488-79c91ad3-4a51-454f-b011-327c88908477.png)
data loader may not influence this a lot.
Is there any way to speed up the model infer speed w/o performance downgrade?

**Comment by amsword** [comment]
you can convert the model and the input to fp16, which will suffer no performance issue as it is trained with fp16.
