### ISSUE TITLE
Video captioning model finetuning

### ISSUE THREAD

**Issue by Tim4ik77** [microsoft/GenerativeImage2Text#40]
Your text gives examples of neural network training for image captioning, but no examples for video captioning. Can you give a code example to solve this problem?

**Comment by amsword** [comment]
you can pay more attention to the following function 
https://github.com/microsoft/GenerativeImage2Text/blob/e1d90a2425e6f4c3e83e6689862b955e0029cbcc/generativeimage2text/train.py#L209

This is for image. For video, the image fields should contain a list of images, instead of one image. That is
https://github.com/microsoft/GenerativeImage2Text/blob/e1d90a2425e6f4c3e83e6689862b955e0029cbcc/generativeimage2text/train.py#L62

Note that, the model can process multiple images, and the code is already in the code.

https://github.com/microsoft/GenerativeImage2Text/blob/e1d90a2425e6f4c3e83e6689862b955e0029cbcc/generativeimage2text/layers/decoder.py#L847

I will keep this in mind and add an example about this when there is bandwidth, but it should be easy to set it up based on the code. Also, feel free to pose any issue when you integrate it.
